spring.datasource.url=jdbc:postgresql://localhost:5432/lego_db
spring.datasource.username=postgres
spring.datasource.password=lego_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
rebrickable.api.key=14bc35cef5fba22514d9ed0eeb78256f