spring.datasource.url=jdbc:postgresql://localhost:5432/lego_db
spring.datasource.username=postgres
spring.datasource.password=lego_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
rebrickable.api.key=1cdd5ac5eabbb7025290590d3ccf740c